[starship]
format = "[\[$time\]](bold yellow) [\[$user\]](bold blue) [\[$directory\]](bold green) [\[$git_branch\]](bold magenta) [\[$git_status\]](bold red) [\[$jobs\]](bold cyan) [\[$character\]](bold white)"

[time]
format = "[%H:%M](bold yellow)"

[user]
format = "[\u](bold blue)"

[directory]
format = "[\[$path\]](bold green)"

[git_branch]
format = "[\($branch\)](bold magenta)"

[git_status]
format = "[\($all\)](bold red)"

[jobs]
format = "[\($symbol\)](bold cyan)"

[character]
format = "[\($symbol\)](bold white)"
symbol = "❯ "
